### PR TITLE
Even more edits

### PR DESCRIPTION
**Pull request by dchelimsky**
Hi Yoko. Here are some more edits that make the language a bit more idiomatic and the music a bit more fun and familiar sounding. I'm going to work on the refactoring part we discussed separately, but please review this for now and let me know if you have any questions.

### CODE REVIEW

**Comment by yokolet** [comment]
Thank you so much!

**Comment by dchelimsky** [comment]
My pleasure! I'd like to get more eyes on this than just yours and mine - who else should we ask to review it?

**Comment by yokolet** [comment]
@howardabrams He wrote the original contents of this app. I pinged him on github, but no response so far. Maybe I should ping him on twitter.

**Comment by howardabrams** [comment]
Bad me! I forgot, but I will review them!

**Comment by dchelimsky** [comment]
@howardabrams please let me know if you have any questions or issues w/ the changes I made. Thanks!

**Pull request merged**
